### ISSUE TITLE
Conversion attempt results in 3kb CBZ files with no images, only the ComicInfo.xml

### ISSUE THREAD

**Issue by bareheiny** [azuravian/cbz_jpg-to-webp#1]
As per the subject - the script correctly identifies archives with jpg files, extracts them to a temp directory and appears to convert them - but only one file is zipped.

If I  stop the script part way through conversion, I cannot locate any .webp files.

Script usage is pretty simple:

  1.  in a CMD window, run "py cbz_JPG-to-WEBP.py"
  2.  set "scan" folder to D:\Testing\Convert
       this folder contains a directory called "Rachel Rising (2011"), which contains a single CBZ archive.
  3. set the "converted" folder to D:\Testing\Convert
  4. set the "corrupt" folder to D:\Testing\Corrupt
  5. watch the progress bars, and note that 25 files are extracted, 24 are converted...but only 1 is zipped

![image](https://user-images.githubusercontent.com/1912425/129833314-2367809f-6a14-432d-97d7-4018f9c36155.png)

Here's a sample file:

OneDrive link:  https://1drv.ms/u/s!AnMfIf1tfCd8gcxln3u85uwZBNdZqQ?e=110E0v

Once you've picked up the file, I'll remove it.

**Comment by azuravian** [comment]
I've downloaded the file.  I've gotta hit the sack, but I'll test tomorrow.

**Comment by bareheiny** [comment]
No rush - my files aren't going anywhere :)

**Comment by azuravian** [comment]
Fixed in latest.
