### ISSUE TITLE
Extracting images line temporarily appears twice during conversion.

### ISSUE THREAD

**Issue by bareheiny** [azuravian/cbz_jpg-to-webp#2]
During conversion, the "Extracting:" line appears twice until the "Converting Images" process has completed - at which point the second "Extracting:" line disappears.

Note that the second "Extracting:" line never seems to get to 100%.

![image](https://user-images.githubusercontent.com/1912425/129986213-8c02111f-aaa3-47dc-84a2-c6e0415a6f60.png)

**Comment by azuravian** [comment]
This is resolved
