### ISSUE TITLE
probably problem with temporary folder (Linux)

### ISSUE THREAD

**Issue by iGom** [azuravian/cbz_jpg-to-webp#4]
I use 5.15.0-2-MANJARO, python 3.9

The script identifies cbz and then creates a temporary folder `\\?\` in the same folder as the script and tries to extracts the first comic there, but fails with the error as it cannot find the directory.

1. in a Linux Terminal, run "py cbz_JPG-to-WEBP.py"
2. set "scan" folder to /home/roro/Downloads/test/
3. this folder contains 11 cbz archives
4. set the "converted" folder to /home/roro/Downloads/test2/
5. set the "corrupt" folder to /home/roro/Downloads/test3/
6. watch the first cbz is extracted then fails

![image](https://user-images.githubusercontent.com/4786772/140660306-683488fb-3e3a-406c-a5a5-2f1c4637f879.png)

the temporary folder `\\?\`
![image](https://user-images.githubusercontent.com/4786772/140660323-3603fc45-145d-4ac0-a919-a9af8afa33f0.png)

**Comment by azuravian** [comment]
Yep, I wrote this originally for Windows.  Let me look through it and see if I can implement an OS check.  There is a path conversion that is required for Windows and I can hopefully just skip that for Linux and make this go away.

**Comment by azuravian** [comment]
This should be resolved
