### ISSUE TITLE
Add resizing option?

### ISSUE THREAD

**Issue by 0xb011** [azuravian/cbz_jpg-to-webp#9]
These days I come across very high quality picture data (in some cases 4000px height for instance).

It would be very nice if you could update the script so that it would shrink down the file whilst retaining the aspect ratio of pictures and using the best method (is Lanczos still the preferred way for shrinking?), before/after (no clue which is better) converting to webp.

I assume we would specify desired height OR width in the first section alongside with other existing parameters.

**Comment by azuravian** [comment]
Hey, this already exists.  I run all of mine using the following command.

path/to/python.exe cbz_JPG-to-WEBP.py -m 1920

The way this flag works is you set the maximum you want in either direction.  It keeps the same aspect ratio, but will make sure the longest side is no larger than 1920px (or whatever you specify).
